name: Pipeline

on: [push, pull_request]

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest
    env:
      BATECT_CACHE_TYPE: directory

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Validate Batect wrapper scripts
        uses: batect/batect-wrapper-validation-action@v0.4.0

      - name: Lint code
        run: ./batect eslint

      - name: Run test
        run: ./batect test
